spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce_db
    username: root
    password: Abhi#01945@740

  jpa:
    hibernate:
      ddl-auto: validate   # dev only
    show-sql: true
    properties:
      hibernate:
        format_sql: true
