spring:
  profiles:
    active: MySQL

  application:
    name: ecommerce-backend


  app:
    jwt:
      secret: ecommerce-secret-key-very-long-and-random-123456789
      expiration-ms: 86400000   # 24 hours

# OAuth2 (Google) placeholders - replace with real client-id and client-secret
  security:
    oauth2:
      client:
        registration:
          google:
            client-id:  ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://www.googleapis.com/oauth2/v4/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: email

  logging:
    level:
      com.abhishek.ecommerce: INFO
  # Dev: do not enable show-sql in production
  # spring.jpa.show-sql=true
  # logging.level.org.hibernate.SQL=DEBUG